#!/usr/bin/env bash
# Opens failed issue URLs in the default browser to allow manual add-to-project.
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/5"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/5" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/5" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/5 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/22"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/22" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/22" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/22 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/21"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/21" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/21" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/21 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/20"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/20" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/20" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/20 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/19"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/19" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/19" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/19 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/18"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/18" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/18" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/18 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/17"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/17" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/17" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/17 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/16"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/16" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/16" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/16 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/15"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/15" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/15" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/15 manually"
echo "Opening https://github.com/diegosantos-ai/pilot-atendimento/issues/14"
python -m webbrowser "https://github.com/diegosantos-ai/pilot-atendimento/issues/14" || xdg-open "https://github.com/diegosantos-ai/pilot-atendimento/issues/14" || echo "Open https://github.com/diegosantos-ai/pilot-atendimento/issues/14 manually"
